# Arbeidskrav 2: Vitenskapsfilosofi  {#assignment2}

## Spørsmål 1 - Induksjon

Et induktivt argument fungerer slik at hvis premissene er sanne, er konklusjonen mest trolig sann, men ikke helt garantert. Induksjon er altså en form for beslutning der man trekker generelle konklusjoner basert på et begrenset utvalg observasjoner (@goodman1983). Ved å bruke induksjon vil det alltid være en grad av usikkerhet involvert. Dette var en teori som den skotske filosofen, David Hume, satte søkelyset på og, og var med på å videreutvikle. Han mente at faktapåstander må undersøkes empirisk, og noen påstander vil ikke undersøkes direkte. En slik påstand vil kreve et svært godt argument for at det skal være rasjonelt å tro på. Et godt argument bør være deduktivt gyldig eller induktivt sterkt, og hvert premiss i argumentet bør være enten en iderelasjon eller støttes av empirisk evidens eller et sterkt argument og argumentet bør være ikke-sirkulært. 

Hvis vi tar den induktive slutningen om at "Solen vil stå opp i morgen», mente Hume at det innebærer et problem av induksjon. Selv om dette har skjedd veldig mange ganger i fortiden, og med stor sannsynlighet også vil skje i fremtiden, kan vi ikke forutse dette aleine. Alle er nødt til å være enig i problemet. Med tanke på at vi ikke kan se inn i framtiden, kan vi heller ikke forutse med sikkerhet hva som kommer til å skje uten at vi forutsetter antagelser om at fremtiden ligner på fortiden. Man er derfor nødt til å gjøre antakelser for at premisset skal gjøre konklusjonen mer sannsynlig. Antakelsen «fremtiden vil være som i fortiden» blir derfor et skjult premiss som er nødt til å være til stede. Dette er en påstand som blir kalt «Uniformitetsprinsippet» (UP), og Hume mente at induktive argumenter ikke kunne forutsees uten bruk av UP. Når vi ser nærmere på UP er det verken en iderelasjon (vi kan ikke bevise at UP er sann gjennom logikk aleine) eller kan empirisk sjekkes direkte. 


Hume mente at en slik induktiv slutning kommer av at mennesket har utviklet en tendens til å forvente hva som kommer til å skje basert på tidligere erfaringer. Han mente at mennesker antar at liknende hendelser vil oppstå også i fremtiden, men dette er ikke en rasjonell begrunnelse, men en vane som har utviklet seg over tid. Vi kan altså ikke gi en logisk begrunnelse for at framtiden vil være lik som fortiden uten å stole på denne usikre antakelsen. Induksjon baserer seg derfor ikke på deduktivt og rasjonelt resonnement, og det blir derfor vanskelig å bruke induksjon som en form for vitenskap. 

For å vise at påstanden «Solen vil stå opp i morgen» begrunner man gjerne påstanden med at «solen har stått opp hver dag i svært lang tid», og «derfor vil solen stå opp i morgen». Selv om argumentet er ikke-sirkulært og premisset er støttet av en iderelasjon eller evidens, er det fortsatt ikke et deduktiv gyldig eller induktivt sterkt. Det er en generell påstand om fremtiden, og vi kan ikke sjekke det her og nå. Man kan begrunne med at UP alltid har vært sann tidligere, og derfor tenke seg at den vil være sann i fremtiden, men da er UP begrunnet med induksjon og for at dette skal stemme må vi igjen anta at UP er sann. Dermed har argumentet blitt sirkulært. Dette betyr at UP er noe vi må anta uten begrunnelse. 

Hume mente derfor at hvert induktive argument i første omgang forutsetter uniformitetsprinsippet. Og i neste omgang at UP ikke har noen rasjonell begrunnelse. Derfor har konklusjonene av alle induktive argument ingen rasjonell begrunnelse. 

På bakgrunn av teorien Hume har kommet med er det vanskelig å være totalt uenig i hans konklusjon. Likevel er det vanskelig å støtte teorien hans fult ut med tanke på at vi hele tiden kommer med induktive argumenter, og noen blir vi overbevist om, mens andre ikke. Dette baserer seg i stor grad på vaner og tidligere erfaringer, og disse mener jeg i noen sammenhenger vil være svært overbevisende og sannsynlige. Når vi ser på påstanden «Solen vil stå opp i morgen», og ikke kan si med full sikkerhet at det vil skje, så mener jeg at det er heller ingenting som tilsier noe annet. Likevel mener jeg det er vanskelig å unngå Humes konklusjon basert på hans begrunnelse, og det vil derfor være vanskelig å løse dette induksjonsproblemet. Likevel vil det være logisk å trekke konklusjoner av visse induktive argumenter med en rasjonell begrunnelse. Vitenskapen har mest sannsynlig også utviklet seg ved å bruke induktive metoder med stor suksess. Vitenskapelige teorier og hypoteser blir hele tiden testes og revurdert, og over tid baserer de seg på empirisk data og eksperimentelle resultater. Dette gir et såpass pålitelig rammeverk for å frembringe kunnskap og forutsi fenomener, selv om det er brukt induktive metoder og argumenter. 


## Spørsmål 2 - Falsifikasjonisme

Falsifikasjonisme er en vitenskapsfilosofisk tilnærming utviklet av Karl Popper. Tilnærmingen baserer seg på testing av vitenskapelige teorier ved å prøve å falsifisere dem, i stedet for å bekrefte dem. Det går ut på å formulere hypoteser som kan testes, og enten bevises eller motbevises gjennom eksperimenter og observasjoner. Dersom teorien ikke er falsifiserbar anses den heller ikke som vitenskap, men som pseudovitenskap eller filosofi. Dette er altså Poppers løsning på avgrensningsproblemet. Vitenskapelige påstander blir skilt fra ikke-vitenskapelige ved at de må være falsifiserbare.   

Falsifikasjonismen fungerer på en måte som beskriver hvordan vitenskapelige teorier utvikles og forbedres over tid. Syklusen starter med å utvikle en hypotese som skal søke etter å forklare en bestemt observasjon eller et fenomen. Hypotesen bør være formulert på en så tydelig og testbar måte som mulig. Hypotesen fører til prediksjoner, helst så presise som mulig og som kan sjekkes empirisk, som igjen fører til falsifisering. Dersom resultatene fra testingen er i strid med hypotesen, anses hypotesen som falsifisert. Hypotesen er ikke lenger en forklaring på fenomenet, og forkastes, og det må dannes en ny hypotese. Dersom hypotesen stemmer, blir den styrket i vitenskapelig verdi, men den kan likevel testes på nytt i fremtiden og stille seg kritisk. Man kan forbedre eller evaluere hypotesen ved å samle mer data eller gjennomføre flere eksperimenter. På denne måten blir det også dannet en ny hypotese, og syklusen fortsetter. Syklusen med utvikling av hypoteser er en kontinuerlig prosess som driver vitenskapelige fremskritt. Det kan være verdt å merke seg at desto flere prediksjoner, eller mer presise prediksjoner, teorien eller uttalelsen innebærer, desto mer falsifiserbar er den (@popper2005).


Ett problem som er sett på innenfor falsifikasjon er knyttet til sannsynlighetspåstander. Når vitenskapsteori er formulert med sannsynlighet eller sannsynlighetsfordelinger blir det utfordrende å fastslå om observasjonene er i tråd med teorien eller ikke. Det dukker altså opp utfordringer knyttet til tolkning av usikkerhet og statistiske variasjoner. Observasjoner i vitenskapen er sjeldent helt presise, og det vil være en grad av usikkerhet rundt målinger. Hvis en teori er beskrevet med sannsynlighetsuttrykk må man vurdere om observasjonene er i samsvar med teoriens forutsagte sannsynlighetsfordeling, eller om de avviker fra det som kan tilskrives statistiske svingninger. I tillegg vil det være vanskelig å avgjøre om avviket skyldes en svakhet i teorien, eller om det er et tilfeldig utfall innenfor en forventet sannsynlighetsgrense, hvis observasjonene fra en teori avviker fra forventningene. 

Dette kan forklares videre med et konkret eksempel knyttet til teori innenfor medisin. Dersom det blir hevdet at en ny medisin er mer effektiv enn en eksisterende behandlinger for en bestemt sykdom, kan den formuleres med sannsynlighetspåstander. For eksempel at det er 95% sannsynlig for at pasienter som tar den nye medisinen vil oppleve en forbedring. Når denne teorien skal testes observeres resultatene og sammenliknes med forventninger fra den sannsynlighetsfordelingen som teorien forutsier. Men selv om teorien antyder at medisinen har en høy sannsynlighet for å være effektiv, er det alltid en viss statistisk usikkerhet knyttet til kliniske forsøk. Målingene kan variere, og dermed kan resultatene avvike fra forventingene, bare på grunn av tilfeldigheter. Variabler som pasientens alder eller påvirkningen fra andre medisiner de tar, kan påvirke resultatet. Det å isolere effekten av medisinen blir vanskelig, og det øker kompleksiteten i tolkninga. Dersom observasjonene ikke samsvarer helt med forventingene, må det vurderes om dette er innenfor det som kan forventes basert på statistiske svingninger eller om det er en svakhet i teorien. Hvor stort avviket må være for at teorien skal forkastes er også en vurdering som må tas. 

En mulig løsning på dette problemet vil være å utvikle kriterier for når avviket mellom observasjonene og teorien blir signifikant nok til å indikere at teorien er problematisk. Det kan altså inkludes av bruken av statistiske tester, som f.eks. i form av p-verdi, og hypotesetesting for å bestemme om observasjonene er innenfor eller utenfor det som kan forventes gitt teoriens sannsynlighetsfordeling. Utfordringen knyttet til sannsynlighetspåstander understreker viktigheten av nøye tolkning av statistiske resultater og bruken av statistiske metoder for å gjøre vitenskapelige konklusjoner. Det vil altså være viktig å vurdere usikkerheten og kompleksiteten nøye, knyttet til både teorien og observasjonene, spesielt når sannsynligheter og statistikker er involvert i vitenskapelige påstander. 