# Arbeidskrav 4: Studiedesign

## Introduksjon

I denne rapporten er det valgt ut fem forskningsstudier som ser på effekten av blokkperiodisering sammenliknet med tradisjonell periodisering: @rønnestad2014a, @rønnestad2014b, @rønnestad2016, @almquist2022 og @breil2010. Studiene er analysert, og det er sett på studiedesign og statistiske analyser. I tillegg vil det bli presentert styrker og svakheter rundt studiene, og avslutningsvis gis det råd om hvordan fremtidige studier bør utformes i henhold til å besvare lignende spørsmål.

Felles for alle studiene er at de ser på blokklegging av utholdenhetstrening (BP = blokk-periodisering) sammenliknet med tradisjonell strukturering av utholdehetstrening (TP = tradisjonell-periodisering). Studiene har sett på blant annet påvirkningen av det maksimale oksygenopptaket (VO$_{2maks}$), laktatterskel, submaksimal og maksimal aerob effekt, prestasjonstester i ulike varianter og hemoglobinmasse (HB$_{mass}$). I studien til Almquist et al. (2022) er det også gjort muskulære analyser av deltakerne. Denne rapporten vil fokusere på hvilken effekt blokklegging har på VO$_{2maks}$. Rapporten tar dermed utgangspunkt i hovedproblemet til alle studiene: hvordan kan man best mulig optimalisere effekten på VO$_{2maks}$ ved å blokklegge utholdenhetstrening, framfor å trene tradisjonelt.  

Utformingen av studiene er naturligvis ikke helt like, og studiene er gjennomført på både syklister (@rønnestad2014a, @rønnestad2014b, @almquist2022), langrennsløpere og skiskyttere (@rønnestad2016) og alpinister (@breil2010). Alle studiene blokklegger høyintensiv trening (HIT), og sammenlikner dette opp mot tradisjonell strukturering av utholdenhetstrening. Tradisjonell utholdenhetstrening omhandler en kombinasjon av lavintensiv trening (LIT) og HIT. 


## Teori

Både LIT og HIT utholdenhetstrening har positive effekter på VO$_{2maks}$ (@helgerud2001; @helgerud2007; @ingham2008). Det ser også ut til at det er nødvendig med en kombinasjon av LIT og HIT for å oppnå optimal utvikling av utholdenhet (@seiler2010). For trente idrettsutøvere ser det likevel ut til at trening nær eller svært nær deres VO$_{2maks}$ er en effektiv stimuli for å ytterligere forbedre denne variabelen (@laursen2002). Hvordan man skal strukturere LIT og HIT for å optimalisere utviklingen er fortsatt noe usikkert, og det er nettopp dette disse studiene i denne rapporter prøver å finne ut av.  

TP av utholdenhetstrening har gjennomgående handlet om to HIT-økter i uka, og tilføyd med LIT (@seiler2004). Blokkperiodisering er kortere perioder (1-4 uker) der hovedfokuset er å forbedre spesifikke egenskaper, som VO$_{2maks}$, og vedlikeholder andre egenskaper. Tanken bak BP av utholdenhetstrening er å gi tilstrekkelig stimuli for å oppnå ytterligere tilpasninger hos godt trente idrettsutøvere, etterfulgt av restitusjon. Noen mener at dette ikke er mulig å oppnå ved et generelt fokus på mange egenskaper samtidig, slik som TP (@issurin2010). Det brede problemet som disse studiene prøver å finne løsningen på er hvordan man skal organisere utholdenhetstrening på for å oppnå en best mulig effekt på utholdenhetsvariabler ved BP, og sammenlikner dette opp med effekten som TP gir. 

Basert på denne teorien har studiene utformet sine egne hypoteser som i hovedsak går ut på at BP vil gi en betydelig større effekt på utholdenhetsvariabelen VO$_{2maks}$ sammenliknet med TP. Studien fra @almquist2022 har ikke utviklet en hypotese eller et spørsmål, men formulerer likevel at målet med studien er å sammenlikne effekten av BP med TP. Det er logisk å tro at BP vil gi en positiv effekt på VO$_{2maks}$, men hvor stor effekten er i forhold til TP er vanskelig å si basert på teori. Utgangsnivået til deltakerne, og hvor mye de har trent tidligere, kan og tenkes å ha betydning for resultatet. Det kan også være logisk å tro at deltakerne vil få en positiv effekt bare av det å endre treningssmønster. Har de trent mange år med TP, kan BP gi en positiv effekt fordi det gir et nytt stimuli.    

## Metode

### Studiedesign

Alle studiene er randomiserte kontrollerte studier (RCT) (@hulley2013). I RCT blir deltakerne tilfeldig delt inn i grupper, og i disse studiene omhandler det to grupper, én intervensjonsgruppe (BP-gruppa) og én kontrollgruppe (TP-gruppa). Dette er et studiedesign som skal minimere skjevheter, og sikre at resultatene blir så pålitelige som mulig. På den måten ser man om resultatene som oppnås av studien har en virkelig effekt, og i hvilken grad. Risikoen for at andre faktorer påvirker resultatet minimeres ved en slik inndeling. Det er omtrent umulig å identifisere og kontrollere alle potensielle faktorer som kan påvirke resultatet, men en randomisering hjelper til med å håndtere ukjente og uobserverte faktorer. Sjansen for at den ene gruppa blir overrepresentert med hensyn til en spesifikk faktor. Ved en randomisering oppnår man en rettferdig sammenlikning mellom de eksponerte individa (BP-gruppa), og de ikke-eksponerte (TP-gruppa) (@hulley2013).  

I alle studiene ble det gjennomført en form for pre-test før gruppene ble randomisert, i form av enten VO$_{2maks}$-test eller gjennomsnittelig effekt over 40 min. Etter at gruppene ble matchet for VO$_{2maks}$ eller gjennomsnittelig effekt ble deltakerne randomisert. Utfallet av dette sørget for at forutsetningene var like, og at det ikke var store skjevheter i VO$_{2maks}$ hos gruppene før intervensjonen startet. Dersom det hadde vært forskjell mellom gruppenes utgangspunkt blir det vanskeligere å si om utfallet av treningsintervensjonen skyldes selve treningen eller treningen basert på utgangspunktet deres. Utgangspunktet og erfaringene til deltakerne skal dermed ikke ha hatt noen påvirkning på resultatet av studiene. To av studiene (@rønnestad2014a; @rønnestad2014b) er basert på samme forskningsprosjekt av samme deltakerutvalg og forskere, men studiene har sett på effekten av BP over henholdsvis fire og tolv uker.
 
Likevel er det litt ulik utforming av studiedesignet i disse fem studiene. I studiene til @rønnestad2014a; @rønnestad2014b; @rønnestad2016; @almquist2022 er treninga til TP-gruppa nøye regulert og tatt kontroll over. På den måten sørger studiene for at de er helt sikre på at organiseringen av utholdenhetstreninga til gruppene er forskjellig. Det totale treningsvolumet av både HIT og LIT, og det totale antall HIT-økter var lik mellom begge gruppene i hver studie. Treninga til BP-gruppa og TP-gruppa er dermed omtrent akkurat den samme, men organisert på forskjellige måter. Det gir stor pålitelighet for at resultatene av studien baserer seg på nettopp det de ønsker å finne ut av, hvilken effekt BP gir på VO$_{2maks}$ sammenliknet med TP.  

I studien til Breil et al. (2010) er det ikke formulert et opplegg til TP-gruppa. Studien har derfor ingen kontroll på hva denne gruppa har utført av trening under intervensjonsperioden. Det gir en større feilkilde når de sammenlikner effekten av BP sammenliknet med TP. 

### Deltakere og rekruttering

I studiene deltok det totalt 19, 15, 19, 30 og 21 (@rønnestad2014a; @rønnestad2014b; @rønnestad2016; @almquist2022; @breil2010) personer, og disse var fordelt tilnærmet likt mellom BP- og TP-gruppene. Dette er et relativt lite utvalg forsøkspersoner, og det gir i utgangspunktet en lav statistisk styrke. Det vil gjøre det vanskelig å påvise en signifikant forskjell mellom de to utvalgene. Likevel hadde studiene et ønske om å ha godt trente utøvere. Alle deltakerne var ansett som godt trente @rønnestad2014a; @rønnestad2014b; @almquist2022 (@pauw2013; @jeukendrup2000), eller klassifisert som eliteutøvere (@rønnestad2016; @breil2010). På den måten treffer studiene ønsket populasjon.

Det vil være utfordrende å få mange reelle deltakere på et så høyt nivå. De personene som kan relatere seg til dette utvalget vil kunne ha stor nytte av denne studien. Studien vil sannsynligvis ikke være like reell for personer som ikke er homogen med dette utvalget. Resultatene fra disse studiene vil dermed være mindre generaliserbare til hele populasjonen. Det kan derfor være verdt å merke seg at studier bør balansere behovet for de som mest sannsynlig vil dra nytte av intervensjonen, mot målet om å rekruttere ønsket utvalgsstørrelse og maksimere generaliserbarhet av studienes funn (@hulley2013).

Deltakerne meldte seg enten på frivillig, (@rønnestad2014a; @rønnestad2014b; @rønnestad2016) eller rekruttert fra lokale sykkel- og alpintlag på og i nærheten av trenings- og testsenter (@almquist2022; @breil2010). De ble informert om risikoer ved deltakelsen på forhånd, og måtte gi sitt skriftlige informerte samtykke før studiedeltakelsen. Disse studiene ble enten godkjent av den lokale etiske komite ved Høgskolen i Lillehammer eller den etiske komiteen i Bern, Sveits, og gjennomført i henhold til Helsinki-erklæringen. 

Ingen av studiene har begrunnet utvalgsstørrelsen, men flere opplyste om frafall av deltakere utover i intervensjonsperioden på bakgrunn av sykdom, medisinske årsaker eller for stor treningsbelastning. Det er dermed ikke gjort noen beregninger på hvor mange deltakere det hadde vært gunstig og hatt med i studiene. En power-beregning burde vært utført fordi det gir en indikasjon på hvor effektiv studien er til å oppdage en faktisk effekt, dersom den eksistere. Man kan altså unngå å tolke manglende signifikans som bevis for å at det ikke er noe effekt, dersom man utfører en power-beregning. Dersom studien har en lav power, er sjansen for å avvise nullhypotesen lav, selv om det faktisk er en effekt til stedet. Det kan dermed bidra til å forhindre en feilaktig konklusjon om mangel på effekt (@pripp2017). 

### Treningsintervensjon

Intervensjonsperioden på studiene varierte fra 11 dager til 12 uker.  BP-gruppene gjennomførte én uke med fem HIT-økter, og tre uker med én HIT-økt, resten LIT (@rønnestad2014a, @rønnestad2014b). I fem ukers studien til Rønnestad et al. (2016) ble det i tillegg lagt inn tre HIT-økter i uke tre. TP-gruppa fordelte ukene sine likt med to HIT-økter, og resten LIT-økter. Sett bort ifra TP-gruppa til Rønnestad et al. (2016) der det i uke tre ble gjennomført like mange HIT-økter som BP-gruppa.  

Studien til @almquist2022 skiller seg ut ved at de blokklagte både HIT, moderat intensivtrening (MIT) og LIT. Det vil si at hver uke i én mesosyklus bestod av én HIT-uke, én MIT-uke og to LIT-uker for BP-gruppa. TP-gruppa kjørte blandingsuker av intensitet, med en syklisk progressiv økning i treningsbelastning gjennom de fire ukene i hver mesosykus.

Studien til Breil et al. (2010) gjennomførte 15 HIT-økter på elleve dager. Hver fjerde dag var en restitusjonsdag, mens det ble gjennomført 1-2 hardøkter på de resterende i form av 4x4 min intervaller. 

Intensitetssonen som er brukt på HIT-øktene i studiene er sone 3, 88-100% av maksspuls (HR$_{maks}$). Dette tilsvarer intensitetssone 4/5 på Olympiatoppens intensitetsskala for utholdenhet (@molmen2019). Alle HIT-øktene ble gjennomført i den spesifikke idretten de ble ansett som utøvere i. HIT-øktene bestod av enten 5x6 min, 6x5 min (@rønnestad2014a, @rønnestad2014b, @rønnestad2016) eller 5x5 min intervaller og MIT-øktene 4x12 min (@almquist2022). Den progressive økningen i treningsbelastning hos TP-gruppa i @almquist2022 studien bestod av HIT-økter med en progresjon de første tre intervalløktene i hver syklus på 4-5-6 x 5 min intervaller og 3-4-5 x 12 min intervaller. I tillegg til puls ble det brukt opplevd anstrengelse i form av Borgs-skala som et mål på intensitet (@almquist2022, @breil2010).

LIT-øktene skulle være på minimum 1 time, og gjennomføres i sone 1 (60-82% av HR$_{maks}$) (@rønnestad2014a, @rønnestad2014b, @rønnestad2016). LIT-øktene kunne gjennomføres i andre bevegelsesformer enn HIT-øktene i alle studiene, men bestod i hovedsak av trening i samme bevegelesform som HIT-øktene. 


### Testing

Før intervensjonsperioden ble det gjennomført pre-tester av ulike varianter. @rønnestad2014a; @rønnestad2014b; @rønnestad2016 og @breil2010 gjennomførte fysiske tester som bestemte VO$_{2maks}$, laktatprofil, maksimal aerob effekt (W$_{maks}$) og prestasjonstester over én eller to testdager. @almquist2022 gjennomførte fysiske tester over to testdager, og så på de samme variablene som de andre studiene. Her ble det også tatt muskelbiopsi, samt HB$_{mass}$. I likhet med denne studien tok også @rønnestad2014b HB$_{mass}$). De fysiske testene ble gjennomført i samme bevegelsesform som HIT-øktene. 
I tillegg til å gjennomføre pre-test gjennomførte alle studiene en lik post-test, enten tre eller syv dager etter intervensjonen. Dette for å sikre at deltakerne var restituert etter treningsperioden. Studiene sørget for at forberedelsene til deltakerne, omstendighetene og testprosedyrene var så like som mulig på begge testene. I studien til @almquist2022 ble det gjennomført fysiske tester også midt i treningsintervensjonen, etter gjennomføring av én mesosyklus (4 uker), før de siste to mesosyklusene startet og gjennomføring av post-test.    

### VO$_{2maks}$

Studiene tar utgangspunkt i variabelen VO$_{2maks}$ når de skal se på effekten av BP på deltakernes utvikling av aerob kapasitet. VO$_{2maks}$ er den høyeste hastigheten på den aerobe energiomsetningen (@åstrand2003), og er derfor regnet som en svært viktig bestemmende faktor for utholdenhetsprestasjon. For utholdenhetsprestasjon vil derfor faktorer som påvirker VO$_{2maks}$ være avgjørende å forbedre. Som skrevet tidligere har både HIT og LIT positiv effekt på aerob utholdenhet, målt som maksimalt oksygenopptak (@helgerud2001; @helgerud2007; @ingham2008). Forbedringer i denne variabelen avhenger av varighet, intensitet, hyppighet, samt genetikk (@shephard1968; @wenger1986). Når utholdenhetsnivået til personer øker, ser det ut til at en økning i intensitet på den aerobe treningen er nødvendig for å oppnå en forbedring i VO$_{2maks}$ (@laursen2002). 

Dette er den utholdenhetsvariabelen som studiene relaterer til i hypotesen, og ønsker å forbedre på bakgrunn av at denne variabelen kan være med på å øke utholdenhetsprestasjon. 

### Statistiske analyser

RCT-studiedesignet gjenspeiler valget av de statistiske analysene. Alle studiene har presentert resultatene som gjennomsnitt ± standardavvik (SD). Det er endringene mellom pre til post mellom gruppene som er interessant og sammenlikne. Alle studiene brukte p<0.05 som signifikansnivå. En toveis variansanalyse (ANOVA) med repeterte målinger ble brukt i de fleste studiene (@rønnestad2014a, @rønnestad2014b, @rønnestad2016, @breil2010), men i noen ulike varianter. @breil2010 regnet ut forskjellen mellom gruppene ved t-test for uparrede tester, mens for å se endringene mellom deltakerne fra pre-post-test ble det brukt t-test for parrede tester. @rønnestad2014a og @rønnestad2014b gjorde først toveis ANOVA på pre-post-verdier, og fant ingen forskjell mellom gruppene. Derfor ble studien videre analysert med t-test og gjennomsnittlig effektstørrelse (ES), begrunnet med et lite utvalgsstørrelse og en forventning om små forbedringer ved godt trente utøvere. ES ble regnet ut som Cohen's d, og kriteriene som var satt som grense for å tolke ES var følgende: 0.0--0.2 triviell, 0.2--0.6 liten, 0.6--1.2 moderat, 1.2--2.0 stor, og >2.0 veldig stor (@hopkins2009). I studien til @rønnestad2016 ble ANOVA bare brukt til å beskrive responser under submaksimale innsatser, mens VO$_{2maks}$, W$_{maks}$ og effekt ved 4 mmol/L ble sammenliknet ved bruk av uparret t-test for å se forskjell mellom gruppene fra pre-post. @breil2010 gjorde også en Turkey´s signifikans post hoc test for å bestemme signifikante forskjeller. 

@almquist2022 brukte heller en blandet lineær modell med grupper definert som «fixed effects» og korregert ved bruk av pre-verdier som en kovarians med software SPSS v.25. Dette gjøres i stedet for ANOVA dersom det er store forskjeller i pre-nivået til mellom gruppene, og det blir derfor brukt pre-verdier som en kovariat i analysen.  



## Resultat

I fire av fem studier økte den relative VO$_{2maks}$ signifikant hos BP-gruppa, mens det ikke var økning hos TP-gruppa. ES av den relative forbedringen i VO$_{2maks}$ viser moderat til høy effeket av BP sammenliknet med TP (@rønnestad2014a, @rønnestad2014b, @rønnestad2016, @breil2010).

I studien til @almquist2022, som gjennomførte VO$_{2maks}$-test etter både uke 4 og 12, var det ingen endring i VO$_{2maks}$ i noen av gruppene. Denne studien blokkperiodiserte både HIT, MIT og LIT, og TP-gruppa hadde en syklisk progressiv økning i belastning utover i hver mesosyklus. 

Hypotesen i hver studiene ble besvart, og stemte overens med resultatet i fire av fem studier. BP ser derfor ut til å være en effektiv måte å forbedre VO$_{2maks}$ på sammenliknet med TP.  


## Diskusjon

Hovedfunnene i denne analysen viser at fire av fem studier viste overlegne effekter på VO$_{2maks}$ ved å drive BP sammenliknet med TP. Konklusjonen til disse studiene var at BP av utholdenhetstrening har overlegne effekter på utholdenhetsvariabelen VO$_{2maks}$ sammenliknet med TP, både når det gjaldt 11 dager eller gikk over en periode på 12 uker. Konklusjonen til @almquist2022 støtter derimot ikke hypotesen om at BP vil forbedre VO$_{2maks}$ ved å periodisere HIT, MIT og LIT framfor en syklisk progressiv økende treningsbelastning som fordeler intensiteten tradisjonelt. 

VO$_{2maks}$ økte til tross for at det totale treningsvolumet, antall hardøkter og tid i sone 3 var lik mellom gruppene (@rønnestad2014a, @rønnestad2014b, @rønnestad2016). Det at studiene har kontrollert treningsintervensjonen til TP-gruppa er en stor styrke ved disse studiene (@rønnestad2014a, @rønnestad2014b, @rønnestad2016, @almquist2022). Resultatene i studiene går dermed direkte på strukturering av utholdenhetstrening. En styrke ved studien til @rønnestad2016 var at de gjennomførte én uke med én ekstra HIT-økt for TP-gruppa. Denne gruppa fikk dermed en litt ekstra stimuli, noe som kunne gitt en potensiell positiv effekt.   

Studien til @breil2010 skiller seg ut ved at TP-gruppa fortsatte sin vanlige trening, noe som førte til forskjellig volum av HIT i gruppene. Det gjør det vanskelig å skille effekten av BP i seg selv, fra forskjellen i HIT-volum. Dette er en svakhet ved denne studien, men i og med at de samme resultatene er funnet i de andre studiene som har kontrollert treningen til begge gruppene, kan det tenke seg at det er struktureringa av treninga som er utslagsgivende. 

En styrke ved sistnevnte studien, var at HIT-øktene ble overvåket og gjennomført av testledere. Intensiteten ble hele tiden kontrollert ved HR$_{maks}$, laktatmålinger og opplevd anstrengelse (Borgs-skala) for å sikre riktig intensitet. I studien til @almquist2022 var deltakerne pålagt å gjennomføre minimum fire hardøkter (2 x HIT og 2 x MIT) under tilsyn av testleder, men kunne gjennomføre alle øktene på denne måten. Det står derimot ingenting om hvor mange som gjennomførte øktene under tilsyn, men da sikret de hvert fall kontroll over noen HIT-økter. Måten @rønnestad2014a og @rønnestad2014b kontrollerte HIT-øktene på var å overvåke kraftutviklingen ved at deltakerne ble utstyrt med en PowerTap SL 2.4 (CycleOps, Madison, WI, USA) montert på bakhjulet, i tillegg til å loggføre opplevd anstrengelse. 

En annen styrke ved studiene er at det blir gjennomført helt like pre- og post-tester, og i samme bevegelsesformen som er brukt i treningsintervensjonen. Forberedelsene og testprosedyren er standardisert slik at det utelukker mulige målefeil, og andre påvirkninger som kunne gitt utslag på resultatet. Siste hardøkt for BP- og TP- gruppa ble gjennomført med lik avstand før post-test, og sikret derfor at deltakerne skulle være likt restituert.  

En svakhet ved studiene er at treningsintervensjonen går over en relativ kort periode (< 12 uker). Flere av studiene ser bare på én treningsintervensjon (@rønnestad2014a, @rønnestad2016, og @breil2010). Det vil være vanskelig å si hvilke effekter BP gir om man fortsetter med denne periodiseringen over en lengre periode. Den kortvarige effekten ser ut til å være positiv, men om utviklingen vil fortsette, stagnere eller få et tilbakefall vil bli synsing. Det kunne derfor vært interessant å sett på en slik BP over en lengre periode. All testing som er gjennomført er også gjort direkte etter intervensjonen. Hvilken effekten BP har gitt etter at det har gått en viss tid er også vanskelig å si noe om. 

For fremtidige studier som skal se på effekten av BP på VO$_{2maks}$, og sammenlikne dette opp mot TP kunne det vært interessant å gjort det over en lengre periode (> 12 uker). Da får man sett effekten på lang sikt. Det å bruke et RCT studiedesign, der man kontrollerer både treninga til BP- og TP-gruppa vil være å foretrekke. Det vil være ressurs- og tidkrevende, men om det hadde vært mulig å gjennomførd alle HIT-økter under kontroll av en testleder, som kan måle intensiteten på øktene sørger man for at alle HIT-øktene blir gjennomført med riktig intensitet. Et større utvalg av forsøkspersoner vil også styrke studiene, men det og ha relativt homogene grupper bør kanskje vurderes som første prioritet likevel.


